// 이 파일은 tools/make_sw.py 로 만든다. 파일을 추가·변경하면 버전을 올려 다시 만든다.
const CACHE = 'dicebound-v1';
const CORE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  './css/style.css',
  './js/data.js',
  './js/game.js',
  './js/main.js',
  './js/pwa.js',
  './js/rules.js',
  './js/ui.js',
  './js/util.js',
  './assets/bg/battle.jpg',
  './assets/bg/cave.jpg',
  './assets/bg/city.jpg',
  './assets/bg/event.jpg',
  './assets/bg/forest.jpg',
  './assets/bg/hell.jpg',
  './assets/bg/menu-wide.jpg',
  './assets/bg/menu.jpg',
  './assets/bg/shop.jpg',
  './assets/bg/snow.jpg',
  './assets/bosses/abyss-dragon.jpg',
  './assets/bosses/fallen-knight.jpg',
  './assets/bosses/hell-lord.jpg',
  './assets/bosses/necromancer.jpg',
  './assets/bossicons/beast.webp',
  './assets/bossicons/crystal.webp',
  './assets/bossicons/demon.webp',
  './assets/bossicons/dragon.webp',
  './assets/bossicons/skull.webp',
  './assets/bossicons/wolf.webp',
  './assets/chars/healer.jpg',
  './assets/chars/innkeeper.jpg',
  './assets/chars/librarian.jpg',
  './assets/chars/merchant.jpg',
  './assets/chars/mystic.jpg',
  './assets/chars/player.jpg',
  './assets/chars/questgiver.jpg',
  './assets/chars/shopkeeper.jpg',
  './assets/chars/villager.jpg',
  './assets/dice/d1.webp',
  './assets/dice/d2.webp',
  './assets/dice/d3.webp',
  './assets/dice/d4.webp',
  './assets/dice/d5.webp',
  './assets/dice/d6.webp',
  './assets/emblems/blue.webp',
  './assets/emblems/gold.webp',
  './assets/emblems/purple.webp',
  './assets/emblems/red.webp',
  './assets/fx/bolt.jpg',
  './assets/fx/burst-fire.jpg',
  './assets/fx/burst-ice.jpg',
  './assets/fx/burst-pink.jpg',
  './assets/fx/burst-purple.jpg',
  './assets/fx/heal.jpg',
  './assets/fx/rune.jpg',
  './assets/fx/shards.jpg',
  './assets/fx/slash-fire.jpg',
  './assets/fx/slash-ice.jpg',
  './assets/fx/void.jpg',
  './assets/fx/vortex.jpg',
  './assets/icons/bleed.webp',
  './assets/icons/block.webp',
  './assets/icons/burn.webp',
  './assets/icons/freeze.webp',
  './assets/icons/heal.webp',
  './assets/icons/px-bag.webp',
  './assets/icons/px-chest.webp',
  './assets/icons/px-potion.webp',
  './assets/icons/px-sword.webp',
  './assets/monsters/goblin.jpg',
  './assets/monsters/golem.jpg',
  './assets/monsters/mage.jpg',
  './assets/monsters/skeleton.jpg',
  './assets/monsters/werewolf.jpg',
  './assets/nodes/battle.webp',
  './assets/nodes/boss.webp',
  './assets/nodes/elite.webp',
  './assets/nodes/event.webp',
  './assets/nodes/mystery.webp',
  './assets/nodes/rest.webp',
  './assets/nodes/shop.webp',
  './assets/nodes/treasure.webp',
  './assets/potions/blue.webp',
  './assets/potions/bomb.webp',
  './assets/potions/crystal.webp',
  './assets/potions/green.webp',
  './assets/potions/red.webp',
  './assets/potions/scroll-open.webp',
  './assets/potions/scroll-roll.webp',
  './assets/potions/vial.webp',
  './assets/relics/altar.webp',
  './assets/relics/amulet.webp',
  './assets/relics/arrow.webp',
  './assets/relics/blue-book.webp',
  './assets/relics/blue-vase.webp',
  './assets/relics/broken-heart.webp',
  './assets/relics/chainmail.webp',
  './assets/relics/chest.webp',
  './assets/relics/crown.webp',
  './assets/relics/dark-ring.webp',
  './assets/relics/gold-tome.webp',
  './assets/relics/green-book.webp',
  './assets/relics/hammer.webp',
  './assets/relics/lantern.webp',
  './assets/relics/leather.webp',
  './assets/relics/pack.webp',
  './assets/relics/purple-chest.webp',
  './assets/relics/purple-gem.webp',
  './assets/relics/purple-tome.webp',
  './assets/relics/ruby-ring.webp',
  './assets/relics/scepter.webp',
  './assets/relics/silver-ring.webp',
  './assets/relics/torch.webp',
  './assets/ui/btn-dark.webp',
  './assets/ui/btn-gray.webp',
  './assets/ui/btn-teal.webp',
  './assets/ui/frame-list.webp',
  './assets/ui/frame-tall.webp',
  './assets/ui/frame-wide.webp',
  './assets/ui/logo.webp',
  './assets/ui/round-mail.webp',
  './assets/ui/round-menu.webp',
  './assets/ui/round-settings.webp',
  './assets/ui/round-share.webp',
  './assets/ui/treasure-glow.jpg'
];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('dicebound-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // 앱 화면은 인터넷이 되면 새 버전을, 안 되면 저장해 둔 버전을 쓴다
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => { const cp = r.clone(); caches.open(CACHE).then(c => c.put('./index.html', cp)); return r; })
      .catch(() => caches.match('./index.html').then(r => r || caches.match('./'))));
    return;
  }
  if (url.origin === location.origin || url.hostname.endsWith('fonts.googleapis.com') || url.hostname.endsWith('fonts.gstatic.com')) {
    e.respondWith(caches.match(req).then(hit => {
      const net = fetch(req).then(r => { if (r && (r.ok || r.type === 'opaque')) { const cp = r.clone(); caches.open(CACHE).then(c => c.put(req, cp)); } return r; }).catch(() => hit);
      return hit || net;
    }));
  }
});
